package com.example.drink_shop.model.enumeration;

public enum Manufacturer {
    NESCAFE, LIPTON, JACOBS, TWININGS, STARBUCKS, TCHIBO, LAVAZZA, ILLY, AHMAD, GREENFIELD, DILMAH, TESS, MAXWELL, ALOKOZAY, HERBATON, BLUE_MOUNTAIN, KOPI_LUWAK, RISTON, BASILUR
}
